# Generated by Django 5.2.8 on 2025-11-25 12:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample_audit_log',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalConditions',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_data', models.JSONField(help_text='JSON containing soil_composition, temperature, humidity, altitude')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'environmental_conditions',
                'indexes': [models.Index(fields=['condition_data'], name='idx_condition_data')],
            },
        ),
        migrations.CreateModel(
            name='ResearcherInfo',
            fields=[
                ('researcher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'researcher_info',
                'indexes': [models.Index(fields=['name'], name='idx_researcher_name'), models.Index(fields=['email'], name='idx_researcher_email')],
            },
        ),
        migrations.CreateModel(
            name='SamplingLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_data', models.JSONField(help_text='JSON containing coordinates, region, country, site_type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sampling_location',
                'indexes': [models.Index(fields=['location_data'], name='idx_location_coordinates')],
            },
        ),
        migrations.CreateModel(
            name='PlantSample',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_detail', models.JSONField(help_text='JSON containing sampling_date, species, common_name, description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(db_column='condition_id', on_delete=django.db.models.deletion.RESTRICT, related_name='samples', to='sampling.environmentalconditions')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.RESTRICT, related_name='samples', to='sampling.samplinglocation')),
            ],
            options={
                'db_table': 'plant_sample',
            },
        ),
        migrations.CreateModel(
            name='GrowthMetrics',
            fields=[
                ('growth_id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('leaf_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('stem_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('50'))])),
                ('health_status', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=50, null=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(db_column='sample_id', on_delete=django.db.models.deletion.CASCADE, related_name='growth_metrics', to='sampling.plantsample')),
            ],
            options={
                'db_table': 'growth_metrics',
                'indexes': [models.Index(fields=['sample'], name='idx_growth_metrics_sample'), models.Index(fields=['measured_at'], name='idx_growth_metrics_measured_at'), models.Index(fields=['health_status'], name='idx_growth_metrics_health')],
            },
        ),
        migrations.CreateModel(
            name='SampleResearchers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, choices=[('lead_researcher', 'Lead Researcher'), ('assistant_researcher', 'Assistant Researcher'), ('field_technician', 'Field Technician'), ('data_analyst', 'Data Analyst'), ('supervisor', 'Supervisor')], max_length=100, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('researcher', models.ForeignKey(db_column='researcher_id', on_delete=django.db.models.deletion.CASCADE, related_name='sample_assignments', to='sampling.researcherinfo')),
                ('sample', models.ForeignKey(db_column='sample_id', on_delete=django.db.models.deletion.CASCADE, related_name='sample_researchers', to='sampling.plantsample')),
            ],
            options={
                'db_table': 'sample_researchers',
                'indexes': [models.Index(fields=['sample'], name='idx_sample_res_sample'), models.Index(fields=['researcher'], name='idx_sample_res_researcher')],
                'unique_together': {('sample', 'researcher')},
            },
        ),
        migrations.AddIndex(
            model_name='plantsample',
            index=models.Index(fields=['location'], name='idx_sample_location'),
        ),
        migrations.AddIndex(
            model_name='plantsample',
            index=models.Index(fields=['condition'], name='idx_sample_condition'),
        ),
        migrations.AddIndex(
            model_name='plantsample',
            index=models.Index(fields=['sample_detail'], name='idx_sample_detail'),
        ),
    ]
