# Generated by Django 5.2.8 on 2025-11-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantsample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
