# Generated by Django 5.2.8 on 2025-11-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0002_plantsample_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantsample',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantsample',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
